POST localhost:5000/api/v1/openBankAccount
Content-Type: application/json

{"accountHolder":  "Laz", "accountType":  "SAVINGS", "openingBalance":  5000}

###
PUT localhost:5000/api/v1/depositFunds/d82bd1e1-0e54-4731-b1e4-802baf3a5d70
Content-Type: application/json

{"amount": 3000}

###

PUT localhost:5000/api/v1/withdrawFunds/d82bd1e1-0e54-4731-b1e4-802baf3a5d70
Content-Type: application/json

{"amount": 4000}

###
DELETE localhost:5000/api/v1/closeAccount/d82bd1e1-0e54-4731-b1e4-802baf3a5d70

###
POST  localhost:5000/api/v1/restoreReadDb

###

GET localhost:5001/api/v1/bankAccountLookup/

###
GET localhost:5001/api/v1/bankAccountLookup/byHolder/Cheikh

###
GET localhost:5001/api/v1/bankAccountLookup/withBalance/GREATER_THAN/1000