POST localhost:5000/api/v1/openBankAccount
Content-Type: application/json

{"accountHolder":  "Laz", "accountType":  "SAVINGS", "openingBalance":  5000}

###
PUT localhost:5000/api/v1/depositFunds/{id}
Content-Type: application/json

{"amount": 3000}

###

PUT localhost:5000/api/v1/withdrawFunds/{id}
Content-Type: application/json

{"amount": 4000}

###
DELETE localhost:5000/api/v1/closeAccount/{id}

###
POST  localhost:5000/api/v1/restoreReadDb

###

GET localhost:5001/api/v1/bankAccountLookup/

###
GET localhost:5001/api/v1/bankAccountLookup/byHolder/{accountHolder}

###
GET localhost:5001/api/v1/bankAccountLookup/withBalance/{equalityType}/{amount}